server:
  port: 10060

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: shop-service
        uri: lb://petshop-server
        predicates:
        - Path=/shop/**
        filters:
        - StripPrefix=1

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:10050/eureka

