server:
  port: 10060

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: shop-service
        uri: lb://petshop-server
        predicates:
        - Path=/shop/**
        filters:
        - StripPrefix=1

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:10050/eureka

---
server:
  port: 10060

spring:
  profiles: peers
  application:
    name: gateway-peers
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: shop-service
        uri: lb://petshop-server
        predicates:
        - Path=/shop/**
        filters:
        - StripPrefix=1

eureka:
  instance:
    hostname: gateway-client-peers
  client:
    serviceUrl:
      defaultZone: http://192.168.31.227:10050/eureka, http://192.168.31.67:10050/eureka