CREATE DATABASE `petshop` /*!40100 DEFAULT CHARACTER SET latin1 */;
DROP TABLE IF EXISTS `pet`;
CREATE TABLE `pet` (
  `PET_ID` varchar(36) NOT NULL DEFAULT 'UUID()',
  `NAME` varchar(50) DEFAULT NULL,
  `TYPE` varchar(20) NOT NULL,
  `QUANTITY` mediumint(9) DEFAULT NULL,
  `PRICE` float DEFAULT NULL,
  `USER_ID` varchar(36) NOT NULL,
  `ACCESSORY_ID` int(11) NOT NULL,
  `DELETED` smallint(6) DEFAULT '0',
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_AT` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`PET_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `USER_ID` varchar(36) NOT NULL DEFAULT 'UUID()',
  `USER_NAME` varchar(50) NOT NULL,
  `PASSWORD` varchar(50) NOT NULL,
  `DELETED` tinyint(4) DEFAULT '0',
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_AT` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;